<!DOCTYPE html>
<html ng-app="inspinia" xmlns="http://www.w3.org/1999/html">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Page title set in pageTitle directive -->
    <title deeplife></title>

    <!-- Font awesome -->
  <!--  <link href="font-awesome/css/font-awesome.css" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="/public/css/bootstrap.min.css" rel="stylesheet">

    <!-- Main Inspinia CSS files -->
    <link href="/public/css/animate.css" rel="stylesheet">
    <link id="loadBefore" href="/public/css/style.css" rel="stylesheet">


</head>

<!-- ControllerAs syntax -->
<!-- Main controller with serveral data used in Inspinia theme on diferent view -->
<body ng-controller="MainCtrl as main"></body>

<!-- Main view  -->
<div ui-view></div>

<!-- jQuery and Bootstrap -->
<script src="/public/js/jquery/jquery-2.1.1.min.js"></script>
<script src="/public/js/plugins/jquery-ui/jquery-ui.js"></script>
<script src="/public/js/bootstrap/bootstrap.min.js"></script>

<!-- MetsiMenu -->
<script src="/public/js/plugins/metisMenu/jquery.metisMenu.js"></script>

<!-- SlimScroll -->
<script src="/public/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Peace JS -->
<script src="/public/js/plugins/pace/pace.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="/public/js/inspinia.js"></script>

<!-- Main Angular scripts-->
<script src="./js/angular/angular.min.js"></script>
<script src="./js/plugins/oclazyload/dist/ocLazyLoad.min.js"></script>
<script src="./js/angular-translate/angular-translate.min.js"></script>
<script src="./js/ui-router/angular-ui-router.min.js"></script>
<script src="./js/bootstrap/ui-bootstrap-tpls-0.12.0.min.js"></script>
<script src="./js/plugins/angular-idle/angular-idle.js"></script>

<!--
 You need to include this script on any page that has a Google Map.
 When using Google Maps on your own site you MUST signup for your own API key at:
 https://developers.google.com/maps/documentation/javascript/tutorial#api_key
 After your sign up replace the key in the URL below..
-->
<!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDQTpXj82d8UpCi97wzo_nKXL7nYrd4G70"></script>-->

<!-- Anglar App Script -->
<script src="/public/js/app.js"></script>
<script src="/public/js/config.js"></script>
<script src="/public/js/translations.js"></script>
<script src="/public/js/directives.js"></script>
<script src="/public/js/controllers.js"></script>


</html>





<?php //echo $this->doctype(); ?>
<!---->
<!--<!--[if IE 9]> <html class="no-js ie ie9 lte9" lang="en" ng-app="skeleton"> <![endif]-->
<!--<html lang="--><?php //echo \Locale::getDefault(); ?><!--" ng-app="skeleton">-->
<!--    <head>-->
<!--        <meta charset="utf-8">-->
<!--        --><?php //echo $this->headTitle()->prepend('deeplife')->setSeparator(' - ')->setAutoEscape(false) ?>
<!---->
<!--        --><?php //echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
<!---->
<!--        <!-- Le styles -->
<!--        <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>-->
<!--        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">-->
<!--        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">-->
<!--        <link href="//cdn.jsdelivr.net/angular.ngtable/0.3.1/ng-table.css" rel="stylesheet">-->
<!---->
<!--        <link rel="stylesheet" href="./css/min.dc46.css" media="screen"/>-->

<!--        <link href="./img/favicon.ico" rel="shortcut icon" type="../image/vnd.microsoft.icon">-->
<!--<link href="./css"-->
        <!-- Language file for javascript translations -->
<!--        <link href="i18n/--><?php //echo \Locale::getDefault(); ?><!--.po" rel="gettext" type="application/x-po">-->

        <!-- Scripts -->
<!--        --><?php //echo $this->headScript(); ?>
<!--    </head>-->
<!---->
<!--    <body>-->
<!---->
<!--        <div id="wrapper">-->
<!---->
<!--            <div id="sidebar-wrapper" class="hidden-print">-->
<!--                <a class="sidebar-brand" href="--><?php //echo $this->url('home') ?><!--"><img src="--><?php //echo $this->basePath('img/logo/logo.png') ?><!--" alt="ZF2"/></a>-->
<!--                <div class="sidebar-nav-container">-->
<!--                --><?php //echo $this->navigation('navigation')->menu()->setUlClass('sidebar-nav'); ?>
<!--                </div>-->
<!--            </div>-->
<!---->
<!--            <div id="page-content-wrapper">-->
<!--                <div class="page-content inset">-->
<!--                    <div class="row">-->
<!--                        <div class="container col-md-8">-->
<!--                            <div class="top-menu hidden-print">-->
<!--                                <a data-toggle="dropdown" href="#"><i class="fa fa-gear settings"></i></a>-->
<!--                                --><?php //echo $this->navigation('secondary_navigation')->menu()->setUlClass('dropdown-menu actions'); ?>
<!--                                <p class="user">-->
<!--                                --><?php
//                              $displayName = $this->zfcUserDisplayName();
//                                if($displayName):
//                                    echo $displayName;
//                                ?>
<!--                                &nbsp;-->
<!--                                <a href="--><?php //echo $this->url('zfcuser/logout'); ?><!--">--><?php //echo 'Logout'; ?><!--</a>-->
<!--                                --><?php //else: ?>
<!--                                <a href="--><?php //echo $this->url('zfcuser/login'); ?><!--">--><?php //echo 'Login'; ?><!--</a>-->
<!--                                --><?php //endif; ?>
<!--                                </p>-->
<!--                            </div>-->
<!---->
<!--                            <div class="hide" app-messages></div>-->
<!---->
<!--                            <div id="container" class="clearfix ">-->
<!--                                <div class="hidden-print">-->
<!--                                   <!-- --><?php
//                                    echo $this->navigation('navigation')
//                                        ->breadcrumbs()
//                                        ->setMinDepth(0)
//                                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
//                                    echo $this->navigation('secondary_navigation')
//                                        ->breadcrumbs()
//                                        ->setMinDepth(0)
//                                        ->setPartial(array('partial/breadcrumb.phtml', 'Application'));
//                                    ?>
<!--                                </div>-->
<!--                                --><?php //echo $this->content; ?>
<!--                                <footer></footer>-->
<!--                            </div>-->
<!---->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!---->
<!--        <!-- Scripts-->
<!--        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
<!--        <script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>-->
<!--        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.20/angular.min.js"></script>-->
<!--        <script type="text/javascript" src="//cdn.jsdelivr.net/angularjs/1.2.20/angular-resource.min.js"></script>-->
<!--        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.10.0/ui-bootstrap.min.js"></script>-->
<!--        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.10.0/ui-bootstrap-tpls.min.js"></script>-->
<!--        <script type="text/javascript" src="//cdn.jsdelivr.net/angular.ngtable/0.3.3/ng-table.js"></script>-->
<!---->
<!--        <script src="./js/min.336e.js"></script>-->
<!---->
<!--        --><?php //echo $this->inlineScript(); ?>
<!--<!---->
<!--    </body>-->
<!--</html>-->
<!--<div id="wrapper">-->
<!---->
<!--<!-- Navigation -->
<!--<div ng-include="'./views/common/navigation.html'"></div>-->
<!---->
<!--<!-- Page wraper -->
<!--<!-- ng-class with current state name give you the ability to extended customization your view -->
<!--<div id="page-wrapper" class="gray-bg {{$state.current.name}}">-->
<!---->
<!--<!-- Page wrapper -->
<!--<div ng-include="'./views/common/topnavbar.html'"></div>-->
<!--<div class="row wrapper border-bottom white-bg page-heading">-->
<!--</div>-->
<!--<div class="row wrapper border-bottom white-bg page-heading">-->
<!--<div class="wrapper wrapper-content animated fadeInRight" ng-controller="modalDemoCtrl">-->
<!--<div class="row">-->
<!--<div class="col-lg-12">-->
<!--<div class="row wrapper border-bottom white-bg page-heading">-->
    <!--<div class="col-lg-10">-->
    <!--<h2>Data Tables</h2>-->
    <!--<ol class="breadcrumb">-->
    <!--<li>-->
    <!--<a href="index.html">Home</a>-->
    <!--</li>-->
    <!--<li>-->
    <!--<a>Tables</a>-->
    <!--</li>-->
    <!--<li class="active">-->
    <!--<strong>Data Tables</strong>-->
    <!--</li>-->
    <!--</ol>-->
    <!--</div>-->
    <!--<div class="col-lg-2">-->

    <!--</div>-->
    <!--</div>-->
    <!--<div class="wrapper wrapper-content animated fadeInRight">-->
    <!--<div class="row">F-->
    <!--<div class="col-lg-12">-->
    <!--<div class="ibox float-e-margins">-->

    <!--</div>-->

    <!--<div>-->
    <!--<div>-->
<!--    <div class="row">-->
<!--        <div class="col-lg-7">-->
<!--            <div class="ibox float-e-margins">-->
<!--                <div class="col-lg-8"></div>-->
<!--                <div class="ibox-content">-->
<!--                    <div class="row">-->
<!--                        <div class="col-lg-2"></div>-->
<!--                        <div class="col-sm-9 m-b-xs">-->
<!---->
<!--                            <div class="btn-group" dropdown >-->
<!--                                <button type="button" class="btn btn-primary btn-sm dropdown-toggle" dropdown-toggle>-->
<!--                                    Action <span class="caret"></span>-->
<!--                                </button>-->
<!--                                <ul class="dropdown-menu" role="menu">-->
<!--                                    <li><a href="">Edit</a></li>-->
<!--                                    <li><a href="">Remove</a></li>-->
<!--                                    <li><a href="">Assign</a></li>-->
<!---->
<!---->
<!--                                </ul>-->
<!--                            </div>-->
<!--                        </div>-->
<!---->
<!--                        <td><button class="btn btn-primary" ng-click="open3()">+ADD</button></td>-->
<!--                        <div class="col-sm-7">-->
<!--                            <div class="input-group"><input type="text" placeholder="Search" class="input-sm form-control"> <span class="input-group-btn">-->
<!--                                        <button type="button" class="btn btn-sm btn-primary"> Go!</button> </span></div>-->
<!--                        </div>-->
<!--                    </div>-->
<!---->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="table-responsive">-->
<!--                <table class="table table-striped">-->
<!--                    <thead>-->
<!--                    <tr>-->
<!--                        <th></th>-->
<!--                        <td>#</td>-->
<!--                        <th>FirstName</th>-->
<!--                        <th>LastName</th>-->
<!--                        <th>Date</th>-->
<!--                        <th>Country</th>-->
<!--                        <th>option</th>-->
<!---->
<!--                    </tr>-->
<!--                    </thead>-->
<!--                    <tbody>-->
<!--                    <tr>-->
<!--                        <td><input icheck type="checkbox" ng-model="main.checkOne"></td>-->
<!--                        <td>1</td>-->
<!--                        <td>-->
<!--                            Cheris-->
<!--                        </td>-->
<!--                        <td>-->
<!--                            Fraud-->
<!--                        </td>-->
<!--                        <td>Jul 14, 2013</td>-->
<!--                        <td>Malawi</td>-->
<!--                        <td><button class="btn btn-primary" ng-click="open4()">Build</button></td>-->
<!---->
<!--                    </tr>-->
<!--                    <tr>-->
<!--                        <td><input icheck type="checkbox" ng-model="main.unCheck1"></td>-->
<!--                        <td>2</td>-->
<!--                        <td>Peter</td>-->
<!--                        <td>-->
<!--                            Haile-->
<!--                        </td>-->
<!--                        <td>jun 9, 2015</td>-->
<!--                        <td>Tanzania</td>-->
<!--                        <td><button class="btn btn-primary" ng-click="open4()">Build</button></td>-->
<!---->
<!--                    </tr>-->
<!--                    <tr>-->
<!--                        <td><input icheck type="checkbox" ng-model="main.unCheck2"></td>-->
<!--                        <td>3</td>-->
<!--                        <td> Mswang</td>-->
<!--                        <td>-->
<!--                            first man-->
<!--                        </td>-->
<!--                        <td>aug 5,2015</td>-->
<!--                        <td>Ethiopia</td>-->
<!--                        <td><button class="btn btn-primary" ng-click="open4()">Build</button></td>-->
<!--                    </tr>-->
<!--                    <tr>-->
<!--                        <td><input icheck type="checkbox" ng-model="main.unCheck3"></td>-->
<!--                        <td>4</td>-->
<!--                        <td>Tamru</td>-->
<!--                        <td>-->
<!--                            Wondemu-->
<!--                        </td>-->
<!--                        <td>jan 12,2015</td>-->
<!--                        <td>Ethiopia</td>-->
<!--                        <td><button class="btn btn-primary" ng-click="open4()">Build</button></td>-->
<!--                    </tr>-->
<!---->
<!--                    <tr>-->
<!--                        <td><input icheck type="checkbox" ng-model="main.unCheck3"></td>-->
<!--                        <td>4</td>-->
<!--                        <td>Herod</td>-->
<!--                        <td>-->
<!--                            Allen-->
<!--                        </td>-->
<!--                        <td>jan 12,2015</td>-->
<!--                        <td>Kenya</td>-->
<!--                        <td><button class="btn btn-primary" ng-click="open4()">Build</button></td>-->
<!--                    </tr>-->
<!---->
<!--                    <tr>-->
<!--                        <td><input icheck type="checkbox" ng-model="main.unCheck3"></td>-->
<!--                        <td>4</td>-->
<!--                        <td>Jeff</td>-->
<!--                        <td>-->
<!--                            Paul-->
<!--                        </td>-->
<!--                        <td>jan 12,2015</td>-->
<!--                        <td>South Africa</td>-->
<!--                        <td><button class="btn btn-primary" ng-click="open4()">Build</button></td>-->
<!--                    </tr>-->
<!--                    </tbody>-->
<!--                </table>-->
<!--                <pagination total-items="main.bigTotalItems" ng-model="main.bigCurrentPage" max-size="main.maxSize" class="pagination-sm" boundary-links="true"></pagination>-->
<!--                <pre>Page: {{main.bigCurrentPage}}</pre>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="col-lg-4" >-->
            <!--<div class="col-md-12">-->
<!--            <div class="ibox-content text-center">-->
<!--                <h1>Additional information</h1>-->
<!--            </div>-->
<!---->
<!---->
<!---->
<!--            <div class="ibox float-e-margins">-->
<!--                <div class="ibox-title">-->
<!--                    <h5>Profile Detail</h5>-->
<!--                </div>-->
<!--                <div>-->
<!--                    <div class="">-->
<!--                        <img alt="image" width="250" height="150" class="img-responsive" src="img/profile_big.jpg">-->
<!--                    </div>-->
<!--                    <div class="ibox-content profile-content">-->
<!--                        <h4><strong>Selected Person Name</strong></h4>-->
<!---->
<!--                        <p><i class="fa fa-map-marker"></i> Place where he/she lives</p>-->
<!--                        <h5>-->
<!--                            About-->
<!--                        </h5>-->
<!---->
<!--                        <p>-->
<!--                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud-->
<!--                            exercitat.-->
<!--                        </p>-->
<!---->
<!---->
<!--                        <div class="user-button">-->
<!--                            <div class="row">-->
<!--                                <div class="col-md-6">-->
<!--                                    <button type="button" class="btn btn-primary btn-sm btn-block"></i> Update Info</button>-->
<!--                                </div>-->
<!--                                <div class="col-md-6">-->
<!--                                    <button type="button" class="btn btn-default btn-sm btn-block"></i> Assign</button>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<!---->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<!--</div>-->
<!---->
<!--<div class="row">-->
<!---->
<!---->
<!--</div>-->
<!---->
<!--</div>-->
<!---->
<!-- Footer -->
<!---->
<!---->
<!--</div>-->
<!-- End page wrapper-->
<!---->
<!--</div>-->
<!--<!--->
<!--</div>-->
<!--</div>- End wrapper-->