<div id="<?php echo $this->id; ?>" class="modal fade">
  <div class="modal-dialog">
    <?php
    $form = $this->form;
    $view = $this->bootstrap();
    $form->prepare();
    echo $view->openTag($form);
    ?>
    <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3><?php echo $this->title; ?></h3>
        </div>
      <div class="modal-body">
        <?php
        $messages = $form->getMessages();
        if (!empty($messages)):
        ?>
        <div class="well">
          <?php print_r($messages); ?>
      </div>
    <?php endif; ?>

      <?php
      foreach ($form as $element) {
          if ($element->getAttribute('name') == 'actions') continue;
          echo $view->row($element);
      }
    ?>
      </div>
      <div class="modal-footer">
        <?php echo $view->row($form->get('actions')); ?>
      </div>
      <?php echo $view->closeTag($form); ?>
    </div>
  </div>
</div>
