<div class="jumbotron">
    <img src="http://www.deeplife.ca/wp-content/uploads/2014/11/Logo-TIFF-file-copy-23-300x86.jpg " alt="DeepLife" id="logo">
    <h1><?php echo $this->translate('Welcome to DeepLife!') ?></h1>
    <p><?php echo sprintf($this->translate('You are currently running the skeleton version %s.'), \Application\Version\Version::VERSION) ?></p>
    <p><?php echo $this->translate('Use the left menu to start managing your items or the top menu to manage your data.') ?></p>
</div>
